# Generated by Django 2.2.14 on 2020-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='gghfhgfhgf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='hgjhgjhgjhgjhg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
